In [1]:
# Import Libararies
import pandas as pd
import numpy as np
import sklearn
from sklearn import datasets

In [2]:
# Load the dataset
iris=datasets.load_iris()
X=iris.data
Y=iris.target

In [3]:
# visualizing the dataset
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [4]:
# Feature names
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
iris.data[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [6]:
# Splitting the Dataset
from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,test_size=0.3)

In [7]:
# Building AdaBoost Model
from sklearn.ensemble import AdaBoostClassifier
ADB=AdaBoostClassifier()
model=ADB.fit(Xtrain,Ytrain)

In [13]:
# Sample Prediction
y_pred=model.predict(Xtest)
y_pred

array([0, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 0, 1, 0,
       1, 2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 2, 0,
       0])

In [14]:
# Evaluating the AdaBoost model
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print('*************  confusion matirx  ***************')
print(confusion_matrix(Ytest,y_pred))
print('\n*************  Classification Report  ***************')
print(classification_report(Ytest,y_pred))
print('*************  Accuracy Score  ***************')
print(accuracy_score(Ytest,y_pred))

*************  confusion matirx  ***************
[[18  0  0]
 [ 0 15  1]
 [ 0  3  8]]

*************  Classification Report  ***************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       0.83      0.94      0.88        16
           2       0.89      0.73      0.80        11

    accuracy                           0.91        45
   macro avg       0.91      0.89      0.89        45
weighted avg       0.91      0.91      0.91        45

*************  Accuracy Score  ***************
0.9111111111111111


In [15]:
# Parameter Tuning using Base estimator
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
svc=SVC(probability=True,kernel='linear')
ADB=AdaBoostClassifier(n_estimators=100, base_estimator=svc, learning_rate=0.01)

In [16]:
# Training and Predicting AdaBoost Classifier
model=ADB.fit(Xtrain,Ytrain)
y_pred=model.predict(Xtest)
y_pred

array([0, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1, 1, 1, 2, 1, 1, 1, 2, 2, 0, 1, 0,
       1, 2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 2, 0,
       0])

In [18]:
# Evaluating the AdaBoost Classifier
print('*************  confusion matirx  ***************')
print(confusion_matrix(Ytest,y_pred))
print('\n*************  Classification Report  ***************')
print(classification_report(Ytest,y_pred))
print('*************  Accuracy Score  ***************')
print(accuracy_score(Ytest,y_pred))

*************  confusion matirx  ***************
[[18  0  0]
 [ 0 15  1]
 [ 0  2  9]]

*************  Classification Report  ***************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       0.88      0.94      0.91        16
           2       0.90      0.82      0.86        11

    accuracy                           0.93        45
   macro avg       0.93      0.92      0.92        45
weighted avg       0.93      0.93      0.93        45

*************  Accuracy Score  ***************
0.9333333333333333
