In [1]:
# Import MNIST Dataset
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [2]:
# Shape of train images
train_images.shape

(60000, 28, 28)

In [3]:
train_images[50]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  12,  56, 140,
        126, 175, 200,  96,   2,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  35, 166, 238, 254, 246,
        242, 253, 246, 254,  67,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [4]:
# Length of train labels
len(train_labels)

60000

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
# Shape of test images
test_images.shape

(10000, 28, 28)

In [7]:
# Length of test labels
len(test_labels)

10000

In [8]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [9]:
# Applying the model
from keras import models
from keras import layers
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [10]:
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [11]:
# Train and Test Dataset
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [12]:
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [13]:
# Setting epochs and find accuracy
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 29s 28ms/step - loss: 0.2584 - accuracy: 0.9247
Epoch 2/5
469/469 [==============================] - 11s 23ms/step - loss: 0.1044 - accuracy: 0.9692
Epoch 3/5
469/469 [==============================] - 18s 38ms/step - loss: 0.0678 - accuracy: 0.9794
Epoch 4/5
469/469 [==============================] - 11s 24ms/step - loss: 0.0486 - accuracy: 0.9856
Epoch 5/5
469/469 [==============================] - 10s 22ms/step - loss: 0.0371 - accuracy: 0.9892


In [14]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

313/313 [==============================] - 3s 6ms/step - loss: 0.0632 - accuracy: 0.9819


In [15]:
# print Accuracy of model
print('test_acc:', test_acc)

test_acc: 0.9818999767303467
